/**
 * Default Presets for Liquid Glass Configurations
 */

export const DEFAULT_PRESETS = {
    "Big pill": {
        rectangleWidth: 375,
        rectangleHeight: 197,
        rectangleCornerRadius: 144,
        edgeDistortionThickness: 29,
        refractionStrength: 47,
        glassBaseColor: [0.9803921568627451, 0.9803921568627451, 1, 0.1],
        frostiness: 1,
        enableChromaticAberration: true,
        chromaticAberrationAmount: 9.1,
        topShadowBlur: 60,
        topShadowOffsetX: -14,
        topShadowOffsetY: 21,
        topShadowOpacity: 0.5,
        bottomGlowBlur: 30,
        bottomGlowOffsetX: 31,
        bottomGlowOffsetY: -15,
        bottomGlowOpacity: 0.3,
        enableReflection: true,
        reflectionBorderThickness: 3,
        reflectionBorderBlur: 0,
        reflectionBorderOffset: 0,
        reflectionStartAngle: 76,
        reflectionOverlayOpacity: 0.8,
        reflectionHighlightSize: 9,
        reflectionTransitionSize: 11.5,
        showGrid: false,
        gridSpacing: 25
    },
    "Big plane": { 
        rectangleWidth: 449,
        rectangleHeight: 510,
        rectangleCornerRadius: 21,
        edgeDistortionThickness: 14,
        refractionStrength: 47,
        glassBaseColor: [0.9803921568627451, 0.9803921568627451, 1, 0.07],
        frostiness: 0,
        enableChromaticAberration: true,
        chromaticAberrationAmount: 9.1,
        topShadowBlur: 60,
        topShadowOffsetX: -24,
        topShadowOffsetY: 24,
        topShadowOpacity: 0.5,
        bottomGlowBlur: 30,
        bottomGlowOffsetX: 19,
        bottomGlowOffsetY: -20,
        bottomGlowOpacity: 0.3,
        enableReflection: true,
        reflectionBorderThickness: 2,
        reflectionBorderBlur: 0,
        reflectionBorderOffset: 0,
        reflectionStartAngle: 272,
        reflectionOverlayOpacity: 0.8,
        reflectionHighlightSize: 9,
        reflectionTransitionSize: 11.5,
        showGrid: true,
        gridSpacing: 25
    },
    "Toolbar": {
        rectangleWidth: 507,
        rectangleHeight: 76,
        rectangleCornerRadius: 21,
        edgeDistortionThickness: 5,
        refractionStrength: 47,
        glassBaseColor: [0.9803921568627451, 0.9803921568627451, 1, 0.07],
        frostiness: 0,
        enableChromaticAberration: true,
        chromaticAberrationAmount: 9.1,
        topShadowBlur: 92,
        topShadowOffsetX: -24,
        topShadowOffsetY: 24,
        topShadowOpacity: 0.5,
        bottomGlowBlur: 11,
        bottomGlowOffsetX: 10,
        bottomGlowOffsetY: -8,
        bottomGlowOpacity: 0.3,
        enableReflection: true,
        reflectionBorderThickness: 2,
        reflectionBorderBlur: 0,
        reflectionBorderOffset: 0,
        reflectionStartAngle: 38,
        reflectionOverlayOpacity: 0.8,
        reflectionHighlightSize: 9,
        reflectionTransitionSize: 11.5,
        showGrid: true,
        gridSpacing: 25
    },
    "Button": {
        rectangleWidth: 339,
        rectangleHeight: 111,
        rectangleCornerRadius: 29,
        edgeDistortionThickness: 29,
        refractionStrength: 27,
        glassBaseColor: [0.9803921568627451, 0.9803921568627451, 1, 0.09],
        frostiness: 1.4,
        enableChromaticAberration: true,
        chromaticAberrationAmount: 7.4,
        topShadowBlur: 60,
        topShadowOffsetX: -14,
        topShadowOffsetY: 21,
        topShadowOpacity: 0.5,
        bottomGlowBlur: 30,
        bottomGlowOffsetX: 31,
        bottomGlowOffsetY: -15,
        bottomGlowOpacity: 0.3,
        enableReflection: true,
        reflectionBorderThickness: 2,
        reflectionBorderBlur: 0,
        reflectionBorderOffset: 0,
        reflectionStartAngle: 251,
        reflectionOverlayOpacity: 0.8,
        reflectionHighlightSize: 9,
        reflectionTransitionSize: 11.5,
        showGrid: false,
        gridSpacing: 25
    }
    
};

export const DEFAULT_PRESET_NAME = "Thick oval";
