/**
 * Default Presets for Liquid Glass Configurations
 */

export const DEFAULT_PRESETS = {
    "Thick oval": {
        rectangleWidth: 333,
        rectangleHeight: 195,
        rectangleCornerRadius: 144,
        edgeDistortionThickness: 29,
        refractionStrength: 47,
        glassBaseColor: [0.9803921568627451, 0.9803921568627451, 1, 0.1],
        frostiness: 1,
        enableChromaticAberration: true,
        chromaticAberrationAmount: 9.1,
        topShadowBlur: 60,
        topShadowOffsetX: -14,
        topShadowOffsetY: 21,
        topShadowOpacity: 0.5,
        bottomGlowBlur: 30,
        bottomGlowOffsetX: 31,
        bottomGlowOffsetY: -15,
        bottomGlowOpacity: 0.3,
        enableReflection: false,
        reflectionArcDegrees: 120,
        reflectionThickness: 20,
        reflectionOffset: 5,
        reflectionOpacity: 40,
        reflectionArcPositionOffset: 0,
        showGrid: false,
        gridSpacing: 25
    },
    "Big pill": {
        rectangleWidth: 275,
        rectangleHeight: 155,
        rectangleCornerRadius: 91,
        edgeDistortionThickness: 22,
        refractionStrength: 55,
        glassBaseColor: [0.9803921568627451, 0.9803921568627451, 1, 0.1],
        frostiness: 1,
        enableChromaticAberration: true,
        chromaticAberrationAmount: 4.1,
        topShadowBlur: 30,
        topShadowOffsetX: 0,
        topShadowOffsetY: 15,
        topShadowOpacity: 0.5,
        bottomGlowBlur: 30,
        bottomGlowOffsetX: 0,
        bottomGlowOffsetY: -15,
        bottomGlowOpacity: 0.3,
        enableReflection: true,
        reflectionArcDegrees: 180,
        reflectionThickness: 7,
        reflectionOffset: 2,
        reflectionOpacity: 100,
        reflectionArcPositionOffset: 0,
        showGrid: false,
        gridSpacing: 25
    },
    "Big plain plane": {
        rectangleWidth: 449,
        rectangleHeight: 510,
        rectangleCornerRadius: 21,
        edgeDistortionThickness: 10,
        refractionStrength: 47,
        glassBaseColor: [0.9803921568627451, 0.9803921568627451, 1, 0.07],
        frostiness: 0,
        enableChromaticAberration: true,
        chromaticAberrationAmount: 9.1,
        topShadowBlur: 60,
        topShadowOffsetX: -24,
        topShadowOffsetY: 24,
        topShadowOpacity: 0.5,
        bottomGlowBlur: 30,
        bottomGlowOffsetX: 19,
        bottomGlowOffsetY: -20,
        bottomGlowOpacity: 0.3,
        enableReflection: false,
        reflectionArcDegrees: 120,
        reflectionThickness: 20,
        reflectionOffset: 5,
        reflectionOpacity: 40,
        reflectionArcPositionOffset: 0,
        showGrid: true,
        gridSpacing: 25
    },
    "Toolbar": {
        rectangleWidth: 507,
        rectangleHeight: 76,
        rectangleCornerRadius: 21,
        edgeDistortionThickness: 5,
        refractionStrength: 47,
        glassBaseColor: [0.9803921568627451, 0.9803921568627451, 1, 0.07],
        frostiness: 0,
        enableChromaticAberration: true,
        chromaticAberrationAmount: 9.1,
        topShadowBlur: 92,
        topShadowOffsetX: -24,
        topShadowOffsetY: 24,
        topShadowOpacity: 0.5,
        bottomGlowBlur: 11,
        bottomGlowOffsetX: 10,
        bottomGlowOffsetY: -8,
        bottomGlowOpacity: 0.3,
        enableReflection: false,
        reflectionArcDegrees: 120,
        reflectionThickness: 20,
        reflectionOffset: 5,
        reflectionOpacity: 40,
        reflectionArcPositionOffset: 0,
        showGrid: true,
        gridSpacing: 25
    }
};

export const DEFAULT_PRESET_NAME = "Thick oval";
